### ISSUE TITLE
remove rule name in favor on a name annotation

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcr#10]
I was thinking we should have an annotation for naming rules such as `@(name my_integers)`.

This would allow naming rules that are embedded in other rules. `[ 2 :0..2 ]` could be `[ 2 @(name my_integers) :0..2 ]`.

Taking this a step further, we could eliminate rule names as the exist today and simply always use the name annotation. So this:

```
[ 2 my_integers, 2 my_strings ]
my_integers :0..2
my_strings ( :"foo" | :"bar" )
```

would turn into this:

```
[ 2 my_integers, 2 my_strings ]
@(name my_integers) :0..2
@(name my_strings) ( :"foo" | :"bar" )
```

This makes the syntax a bit more simple (I think). As of now, a ruleset is composed of a series of rules (and directives) where each rule is composed of a rule name and rule definition. Making the name an annotation means that a ruleset is a series of rules, and rules are rule definitions.

What do you think?

**Comment by anewton1998** [comment]
Of course, I should have stated that it is also possible to have the name annotation and still maintain the rule name in the syntax the way it is. And that might be the best thing to do.

**Comment by codalogic** [comment]
Seems not having forked this repo I wasn't watching it, so I missed these comments!  I should now be watching.

I would stick with rule names as they are for the moment.  This gives us an optimisation of what we can already do.  For the time being I'd keep it as simple as possible and keep this for rev 2 if there's demand for it.

**Comment by anewton1998** [comment]
I agree. Closing this issue.
