### ISSUE TITLE
root_rule mapping to a group_rule

### ISSUE THREAD

**Issue by codalogic** [arineng/jcr#12]
We allows root_rule to map to a group_rule.  Does that mean any of the members of the group can act as group rules?  e.g. if we have JCR of:

```
( { "foo" : string } | { "bar" : string } )
```

does that mean the following is a valid JSON instance:

```
{ "foo" : "baz" }
```

and so is:

```
{ "bar" : "baz" }
```

If so, does the I-D need updating to cover this?

**Comment by anewton1998** [comment]
Yes, the I-D needs updating to note this is possible. In my opinion, the difference between a root rule that is a group rule and multiple root rules is a matter of style. We should call it out though.

**Comment by codalogic** [comment]
Sounds good.  I guess you might want to write it up before closing it, but it's all good by me.

**Comment by anewton1998** [comment]
done
