### ISSUE TITLE
integer and floats of different bit sizes

### ISSUE THREAD

**Issue by codalogic** [arineng/jcr#17]
Following online discussion, we could consider adding types of int8, uint8, int16, uint16, int32, uint32, int64, uint64, int128, uint128, bigint, float, double and decimal.  While some aspects of this can be expressed using ranges, it may be appropriate to include the above as shorthand, easy to remember types.

In the above naming, `bigint` would be arbitrary precision integer.  `decimal` would be an arbitrary precision number that included decimal places.

**Comment by codalogic** [comment]
On JSON list discussion it emerged that a number of languages, including JavaScript use double precision floating point numbers to store integers.  This equates to 54-bit integer values.  Hence we can consider adding int54 and uint53 (or int53 and uint52 as internet searches suggest that int53 is more common although possibly an incorrect representation of the real precision due to FP's implied leading 1)

**Comment by anewton1998** [comment]
So it strikes me that uint8 is just 0..255 and int16 is -32768..32767 and so forth. It seems to me we should just support intXX and uintXX, etc... because as far as an implementation goes, uint64 and uint128 may just be the same code path with different constants.

As for double, what standard is that. IEEE854?

**Comment by codalogic** [comment]
Not sure if by "just support intXX and uintXX" you mean "only support intXX.." or "support intXX.. as well".  I think we should do both intXX and uintXX, and m..m number ranges.  As you say, intXX / uintXX are basically convenient front-ends to specify max and min for numbers that we already support via the n..m number ranges.

I'd expect things like int32 and uint32 to be used most of the time, but where there's a need to express a specific n..m range I think we should support that.  We have an elegant solution for doing it, it's not hard and it allows rule-sets to be expressive.

(Discarded thought: I did consider that we could define a library along the lines of:

```
int8 : -128..127
uint8 : 0..255
etc
```

then have something like:

```
#import http://json-content-rules.org/numbers as num
{ "count" : num.int8 }
```

But since such numbers would be so common I think they should just be built-in.)

**Comment by codalogic** [comment]
Oh, and I'm thinking:

float = IEEE 754 32-bit format
double = IEEE 754 64-bit format

I think these are pretty standard in the C influenced world, and ubiquitous on hardware.

**Comment by anewton1998** [comment]
What I meant is that we support arbitrary bit sizes.

```
intxx = "int" integer
uintxx = "uint" integer
```

**Comment by codalogic** [comment]
So that includes int1, int2, int3 etc.?  

If someone does int2048 (maybe for crypto), do we leave it to the 'implementation' to be able to take the contents of a string and represent it as a JSON number?  Or do we say an implementation may be restricted to a maximum XX of 54 inline with the text on the JSON RFC?

**Comment by anewton1998** [comment]
We'll probably need to draw a distinction between what can be put in JCR, and what a JCR validator MUST or MAY do. As far as a specification, the sky is the limit. But a validator MUST support XX (whatever the 64bit equivalents are) and MAY support ranges greater.

How does that sound?

**Comment by codalogic** [comment]
The JSON RFC talks about 2^53 as this is the largest integer you can store in a double, which is the default number type for JavaScript, Ruby(?), PHP and other such scripting languages.  Maybe we should use words that follow that rule?

Then again, in an IoT world, will all processors have FPUs?  Will int32 be as big as you can reliably get?

Perhaps we can't specify a minimum supported size and just say it's up to an implementation to assess whether a processing environment can support the necessary integer size?

**Comment by codalogic** [comment]
Done
