### ISSUE TITLE
Allow multiple nameless root rules

### ISSUE THREAD

**Issue by codalogic** [arineng/jcr#21]
Recent email discussions raised the issue that we discussed allowing a single nameless root rule a while back (https://github.com/arineng/jcrvalidator/issues/20).  What we didn't do it allow multiple nameless root rules.  I'm not sure if this was conscious decision, or just didn't occur to us at the time (the use-case was such that it didn't push allowing multiple to the fore).  Since we allow the single nameless rule as:

```
( {...} | {...} | {...} )
```

We could change the ABNF to:

```
rule(:jcr) { ( spcCmnt | directive ).repeat >> ( spcCmnt | directive | root_rule | rule ).repeat }
#! jcr = *( sp-cmt / directive / root_rule / rule )
```

to allow:

```
{...}
{...}
{...}
```

This also allows a single root rule at top or bottom depending on personal preference.

I've done a local test of the ABNF and all seems OK.  If this seems the way to go I could do a formal pull request when the colon work has settled out more.

**Comment by anewton1998** [comment]
Sounds good to me. Yes, please hold up on the PR as the ABNF is changing / has changed quite a bit.

**Comment by codalogic** [comment]
I think we can close this one?  It's done.
