### ISSUE TITLE
Repetition step

### ISSUE THREAD

**Issue by codalogic** [arineng/jcr#23]
While we're discussing repetition (hopefully soon, never to return to :-) ), with the new syntax we have the option to specify the modulo of valid repeats.  i.e. we could specify pairs of floats by doing:

```
"coords" : [ float @*%2 ]
```

where `%` indicates that there is a repetition step, and the p_integer thereafter specifies what a valid instance repetition must be divisible by.

I mention it because I recall an example in XSD1.1 that used `xs:assert` to specify such a constraint.  We could do this with JCRCC as:

```
"coords" @{assert count($) % 2==0} : [ float @* ]
```

It maybe that JSON doesn't really need this, whereas XML does.  JSON could do it as:

```
"coords" : [ [ float @2 ] @* ]
```

whereas XML can't do this for an attribute, and it would be verbose for elements:

```
<coords><coord>10.0 5.3</coord><coord>11.6 15.9</coord></coords>
```

This is not something I feel strongly about.  It's a "while we're on the subject" thought.  We can either dismiss it as "thought about, but discarded" or just leave it as an issue to think about in the future.

**Comment by anewton1998** [comment]
This _sounds_ simple to implement. Let me try it out, and if it works out I say yes.

**Comment by anewton1998** [comment]
This is not implemented in the jcr validator and now in the 07 draft.
