### ISSUE TITLE
Trivial point: ip4 vs. ipv4, ip6 vs. ipv6

### ISSUE THREAD

**Issue by johnwcowan** [arineng/jcr#24]
I think people are more used to writing "ipv4" (or actually "IPv4") than "ip4".  Incredibly minor, but why not.

**Comment by anewton1998** [comment]
I disfavor the capitalization, but "ipv4" / "ipv6" works. Also thinking we should just add an "ip".

**Comment by codalogic** [comment]
I would tend to write ipv4/ipv6, but is that the IETF's preferred format?  I don't know.

Other than that, I agree about keeping it lower case for consistency with the rest.

If I'd come up with this by myself I'd make `ip` be `ipaddr`, but I can easily go with either.

**Comment by anewton1998** [comment]
alright, `ipv4`, `ipv6` and `ipaddr`. That's good enough.
