### ISSUE TITLE
base64 or base64url or both

### ISSUE THREAD

**Issue by codalogic** [arineng/jcr#25]
We have a tag for base64, but I-JSON (rfc7493) recommends using base64url.  Should we do that too?  Instead of base64 or in addition to base64?

**Comment by anewton1998** [comment]
Those come from https://tools.ietf.org/html/rfc4648

Perhaps all of them: base16, base32, base32 extended, base64, and base64 url.

And believe it or not, I've run into base32 extended in the wild. Doing validation on these isn't hard.

**Comment by codalogic** [comment]
I'm hoping that one day there will be one baseXX to rule them all, in the same way the UTF-8 is the UTF to rule them all (on the wire anyway).  I was hoping for base64url, but maybe JCR is not the place to push the agenda!

**Comment by codalogic** [comment]
As mentioned in the pull request, I've done hex, base32, base32hex, base64, and base64url.  If you want to change any of that let me know, or you can close this one.
