### ISSUE TITLE
Allow regular expression flags

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcr#6]
Should the syntax allow regular expression flags?

**Comment by codalogic** [comment]
We would need to require spcCmnt after a regular expression to make it unambiguous.  We already need this after a uri template.  Perhaps we should just make it that primitive_rule should end with spcCmnt.  That allows us to do:

```
rule1:/abc/i rule2:integer
```

and also:

```
rule1:(:/abc/i|:integer)    ; No space after /i
```

(For those that have good eye sight!)

**Comment by anewton1998** [comment]
Not that I'm against your idea, but can't we just limit the flags specifically since there are only a handful of them?

**Comment by codalogic** [comment]
I'm thinking that without the space the following would be ambiguous:

```
rule:/abc/identifier:"id":string
```

Is that a regex with the /i modifier and rule name 'dentifier' or no regex modifier and rule name 'identifier'?

I am assuming using the Perl approach to modifiers here (of which I figure the i, s and x ones are the ones we want?).  Do you have an alternative in mind?

**Comment by anewton1998** [comment]
Ah. No, you've explained why I am wrong. I think requiring spcCmnt is perfectly acceptable.

**Comment by codalogic** [comment]
There might be a question of where the spcCmnt goes.  For example, it would be nice to allow:

```
rule [ :/abc/i, :integer, :string ]
```

Maybe it should go at the end of the :rule definition?  That would make the following illegal, but I think it's OK:

```
rule:integeridentifier:integer
```

instead requiring:

```
    rule:integer identifier:integer
```

**Comment by codalogic** [comment]
Thinking about it over night, I've changed my opinion!

I'm thinking that the following:

```
rule:/abc/identifier"id":string
```

would be interpreted as a regex with the /i modifier and rule name 'dentifier'.  That's what a depth first parser would come up with.  If you want no regex modifier and rule name 'identifier' then you have to put the space in.

I imagine people would normally put some sort of separator / white space in anyway so compromising the ABNF to address this by forcing a space where it's not really required seems the wrong way to go.

A similar situation exists with uri-templates.

I imagine this is closer to what you were originally thinking as well.

**Comment by anewton1998** [comment]
Yes, that's what I was thinking... just stated more clearly.

What I think we don't want is `rule :string` ... that is forcing people to put spaces after rules. That just seems quirky.

**Comment by codalogic** [comment]
Agreed.

So if we add a `match('[isx]')...` to regex of parser.rb should that be sufficient for what we need?  Are the i, s and x flags the correct ones?

**Comment by anewton1998** [comment]
Yes, I think `isx` are the only ones we need.

**Comment by codalogic** [comment]
OK.  Shall I mod parser.rb, create some tests and do a pull request for that?

**Comment by anewton1998** [comment]
That would be fantastic

**Comment by anewton1998** [comment]
This was done. closing.
