### ISSUE TITLE
annotation for calling custom code to evaluate rules

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcr#9]
Regarding the topic of annotations to call custom code for evaluating rules, in the issue on the jcrvalidator I speculated with something like:

```
odd_int @(check-code my_code) : integer

# code my_code(ruby-2.0)
## def my_def data
##   return data % 2
## end
```

I'm now thinking this is a bad idea. Embedding code in a ruleset invites all the headaches with variable scope and library paths, etc... If people want to pass around code, they can do that via GitHub. Or if they feel they must put it in an RFC, they can provide the actual code alongside the ruleset.

I propose we simply allow an annotation to link a rule to an entry point in the custom code. The only thing we need to do is say that the custom code either produces a positive evaluation or a negative evaluation.

I think this is what we want:

```
odd_int @(call my_code) : integer
```

**Comment by codalogic** [comment]
I agree we're not ready to tackle this yet.  We could even be even more abstract and have something like:

```
odd_int @(satisfies my_constraint) : integer
```

Where the meaning of `my_constraint` is "beyond the scope of this document".  For example, there could be a section in an RFC that narratively describes each constraint in a non-code manner.  It's up to the ruleset designer to decide how this should be done and is not expected to be machine parsable.

My other thought is that if we get clever at some point in the future we might want to have annotations along the lines of:

   strange_int @(assert ($ % 3 == 0) && ($ % 5 == 0) ) : integer

i.e. include parentheses within the annotation.  If that's a possibility it might be worth changing the annotation format now to use curly braces so we get something like:

   strange_int @{assert ($ % 3 == 0) && ($ % 5 == 0) } : integer

**Comment by codalogic** [comment]
I've been thinking about this some more, and to future proof us I think we should allow multi-line directives along the lines of:

```
#{constraint foo
    a_condition &&
    another_condition
}
```

I'll write up some thoughts that I've been having on how we can take advantage of that, but this and adopting annotations like @{...} is the tl;dr.

**Comment by codalogic** [comment]
Note to self: We should allow q_strings and regexes (that may possibly include '}' characters) in annotations and multi-line directives.  Hence annotation_parameters needs to look something like:

```
(match('[^}"/]') | q_string | regex).as(:annotation_parameters)
```

**Comment by anewton1998** [comment]
I like the idea of multiline directives and changing the syntax of annotations.

**Comment by codalogic** [comment]
I can have a go at doing this Monday if you like.  But if you want to do it sooner then feel free.

**Comment by anewton1998** [comment]
multiline directives are in.
the rest we are either dropping or is being covered by co-constraints.
